package com.mapper;

import com.model.YueTest2;
import com.model.YueTest2Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface YueTest2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    long countByExample(YueTest2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int deleteByExample(YueTest2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int insert(YueTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int insertSelective(YueTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    List<YueTest2> selectByExample(YueTest2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    YueTest2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") YueTest2 record, @Param("example") YueTest2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int updateByExample(@Param("record") YueTest2 record, @Param("example") YueTest2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int updateByPrimaryKeySelective(YueTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yue_test2
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    int updateByPrimaryKey(YueTest2 record);
}