package com.model;

import org.omg.CosNaming.NamingContextExtPackage.StringNameHelper;

import java.io.Serializable;

public class Admin implements Serializable {
    public Admin(){

    }

    public Admin(int id, String name, int age){
        this.id=id;
        this.name=name;
        this.age=age;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.Id
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.name
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.age
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.Id
     *
     * @return the value of Admin.Id
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.Id
     *
     * @param id the value for Admin.Id
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.name
     *
     * @return the value of Admin.name
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.name
     *
     * @param name the value for Admin.name
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.age
     *
     * @return the value of Admin.age
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.age
     *
     * @param age the value for Admin.age
     *
     * @mbg.generated Wed Nov 29 14:56:55 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}