package com.model;

public class YueTest2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test2.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test2.test2_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private String test2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test2.age
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test2.test1_id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private Integer test1Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test2.id
     *
     * @return the value of yue_test2.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test2.id
     *
     * @param id the value for yue_test2.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test2.test2_name
     *
     * @return the value of yue_test2.test2_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public String getTest2Name() {
        return test2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test2.test2_name
     *
     * @param test2Name the value for yue_test2.test2_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setTest2Name(String test2Name) {
        this.test2Name = test2Name == null ? null : test2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test2.age
     *
     * @return the value of yue_test2.age
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test2.age
     *
     * @param age the value for yue_test2.age
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test2.test1_id
     *
     * @return the value of yue_test2.test1_id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public Integer getTest1Id() {
        return test1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test2.test1_id
     *
     * @param test1Id the value for yue_test2.test1_id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setTest1Id(Integer test1Id) {
        this.test1Id = test1Id;
    }
}