package com.model;

public class YueTest1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test1.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yue_test1.test1_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    private String test1Name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test1.id
     *
     * @return the value of yue_test1.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test1.id
     *
     * @param id the value for yue_test1.id
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yue_test1.test1_name
     *
     * @return the value of yue_test1.test1_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public String getTest1Name() {
        return test1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yue_test1.test1_name
     *
     * @param test1Name the value for yue_test1.test1_name
     *
     * @mbg.generated Sat Feb 29 01:02:45 CST 2020
     */
    public void setTest1Name(String test1Name) {
        this.test1Name = test1Name == null ? null : test1Name.trim();
    }
}